name: Bitbake Release

on:
  release:
    branches: 
    - main
    types: [published]
    
jobs:
  machine-matrix:
    runs-on: [self-hosted, linux]
    timeout-minutes: 1440

    strategy:
      fail-fast: false
      
    steps:
      - name: Show release event information
        run: |
          echo "release.name        = ${{ github.event.release.name }}"
          echo "release.body        = ${{ github.event.release.body }}"
          echo "release.upload_url  = ${{ github.event.release.upload_url }}"
          echo "release.html_url    = ${{ github.event.release.html_url }}"
          echo "release.tag_name    = ${{ github.event.release.tag_name }}"
          echo "release.draft       = ${{ github.event.release.draft }}"
          echo "release.prerelease  = ${{ github.event.release.prerelease }}"

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Clone required dependencies
        run: ./repo-mgr.sh init
      
      - name: Run build
        run: ./run-build.sh

      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./build/tmp/deploy/images/*/*.rootfs.wic.gz
          retention-days: 5

      - name: Upload release images
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build/tmp/deploy/images/*/*.rootfs.wic.gz

      - name: Disk space report after build
        run: |
          echo "Memory and swap:"
          free
          echo
          swapon --show
          echo
          echo "Available storage:"
          df -h
          echo
